package com.meu.pdf;

import com.jgoodies.looks.plastic.PlasticLookAndFeel;
import com.jgoodies.looks.plastic.theme.DarkStar;
import com.meu.dao.Banco;
import com.meu.model.Parametros;
import com.meu.model.Item;
import com.meu.model.PdfModel;
import com.meu.seguranca.ControlaAcessoGUI;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Éder Mello
 */
public class Pdf extends javax.swing.JFrame {

    private Banco banco;

    private String pathDatabase;
    private String ipHost;
    private String porta = "";
    private String user = "FSCSIA";
    private String senha = "csfais";
    private static PdfModel pdfModel;
    private boolean isLogado;

    /**
     * Creates new form Pdf
     */
    public Pdf() {

//        lookTela();
        this.setTitle("Leitor de PDF");
        if (ControlaAcessoGUI.isValidaTempoLicenca()) {
            isLogado = true;//ControlaAcessoGUI.autenticador();

            if (isLogado) {
                initComponents();

                this.setLocationRelativeTo(null);
                this.prepareConexaoComBanco();

                pdfModel = new PdfModel();
                PdfModel.inicializePdfModel();
                btn.setBackground(Color.RED);
                caminhoArquivos.setText(System.getProperty("user.dir"));
                caminhoBanco.setText(System.getProperty("user.dir") + File.separator + "SEDFIORILLI.FDB");
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
//                lookTela();
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "SENHA OU USUÁRIO INCORRETOS", ".: SEM AUTORIZAÇÃO :.",
                        JOptionPane.ERROR_MESSAGE);
                Runtime.getRuntime().exit(0);
            }
        } else {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,
                    "Por razões de segurança esta aplicação\n"
                    + "não poderá funcionar até ser atualizada!",
                    ".: Atualização Necessária! :.",
                    JOptionPane.ERROR_MESSAGE);
            Runtime.getRuntime().exit(0);
        }
        ////////////////////////////////////////

    }

    private void lookTela() {
        try {
            PlasticLookAndFeel.setPlasticTheme(new DarkStar());
            try {
                UIManager.setLookAndFeel("com.jgoodies.looks.plastic.Plastic3DLookAndFeel");
            } catch (InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                JOptionPane.showMessageDialog(null, "erro");
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "erro");
        }

        SwingUtilities.updateComponentTreeUI(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        exercicio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        caminhoArquivos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        portaBanco = new javax.swing.JTextField();
        boxCodigo_cax_doc = new javax.swing.JComboBox<>();
        boxCodigo_cls_doc = new javax.swing.JComboBox<>();
        boxCodigo_tipo_doc = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        caminhoBanco = new javax.swing.JTextField();
        btnCaminhoBanco = new javax.swing.JButton();
        btnCaminhoArquivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        selecionarArquivo = new javax.swing.JMenuItem();
        selecionarPasta = new javax.swing.JMenuItem();
        ultimo = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        ajuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setText("Tipo de Documento");
        desktopPane.add(jLabel4);
        jLabel4.setBounds(10, 60, 250, 15);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setText("Caixa do Arquivo");
        desktopPane.add(jLabel6);
        jLabel6.setBounds(10, 110, 130, 15);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setText("exercicio (2020):");
        desktopPane.add(jLabel7);
        jLabel7.setBounds(10, 160, 120, 15);

        exercicio.setText("2020");
        exercicio.setToolTipText("");
        exercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exercicioActionPerformed(evt);
            }
        });
        desktopPane.add(exercicio);
        exercicio.setBounds(10, 180, 120, 24);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel9.setText("Classificação do Documento");
        desktopPane.add(jLabel9);
        jLabel9.setBounds(10, 10, 180, 15);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setText("Caminho dos arquivos:");
        desktopPane.add(jLabel2);
        jLabel2.setBounds(10, 210, 160, 15);
        desktopPane.add(caminhoArquivos);
        caminhoArquivos.setBounds(10, 230, 360, 24);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel10.setText("Caminho do Banco:");
        desktopPane.add(jLabel10);
        jLabel10.setBounds(10, 310, 130, 15);

        portaBanco.setText("3050");
        portaBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portaBancoActionPerformed(evt);
            }
        });
        desktopPane.add(portaBanco);
        portaBanco.setBounds(10, 280, 120, 24);

        boxCodigo_cax_doc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        desktopPane.add(boxCodigo_cax_doc);
        boxCodigo_cax_doc.setBounds(10, 130, 210, 26);

        boxCodigo_cls_doc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        desktopPane.add(boxCodigo_cls_doc);
        boxCodigo_cls_doc.setBounds(10, 30, 210, 26);

        boxCodigo_tipo_doc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        boxCodigo_tipo_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxCodigo_tipo_docActionPerformed(evt);
            }
        });
        desktopPane.add(boxCodigo_tipo_doc);
        boxCodigo_tipo_doc.setBounds(10, 80, 210, 26);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel11.setText("Porta:");
        desktopPane.add(jLabel11);
        jLabel11.setBounds(10, 260, 130, 15);
        desktopPane.add(caminhoBanco);
        caminhoBanco.setBounds(10, 330, 360, 24);

        btnCaminhoBanco.setText("jButton1");
        btnCaminhoBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaminhoBancoActionPerformed(evt);
            }
        });
        desktopPane.add(btnCaminhoBanco);
        btnCaminhoBanco.setBounds(370, 330, 30, 26);

        btnCaminhoArquivo.setText("...");
        btnCaminhoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaminhoArquivoActionPerformed(evt);
            }
        });
        desktopPane.add(btnCaminhoArquivo);
        btnCaminhoArquivo.setBounds(370, 230, 30, 26);

        jLabel1.setText("Leitor de PDF - É.M .Software - v.1.0");

        btn.setForeground(new java.awt.Color(0, 0, 0));
        btn.setText("Conectar");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("Arquivo");

        selecionarArquivo.setMnemonic('o');
        selecionarArquivo.setText("Selecionar (Arquivos)");
        selecionarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarArquivoActionPerformed(evt);
            }
        });
        fileMenu.add(selecionarArquivo);

        selecionarPasta.setMnemonic('a');
        selecionarPasta.setText("Selecionar (Pastas)");
        selecionarPasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarPastaActionPerformed(evt);
            }
        });
        fileMenu.add(selecionarPasta);

        ultimo.setMnemonic('s');
        ultimo.setText("Ultimo");
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });
        fileMenu.add(ultimo);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Sair");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        ajuda.setText("Ajuda");

        jMenuItem1.setText("Ajuda doc.");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ajuda.add(jMenuItem1);

        menuBar.add(ajuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencheBox() {

        ArrayList<Item> itens = pdfModel.boxCodigo_cax_doc(banco);

        itens.forEach((item) -> {
            boxCodigo_cax_doc.addItem(item.getCodigo() + " - " + item.getDescricao());
        });

        itens = pdfModel.boxCodigo_tipo_doc(banco);

        itens.forEach((item) -> {
            boxCodigo_tipo_doc.addItem(item.getCodigo() + " - " + item.getDescricao());
        });

        itens = pdfModel.boxCodigo_cls_doc(banco);

        itens.forEach((item) -> {
            boxCodigo_cls_doc.addItem(item.getCodigo() + " - " + item.getDescricao());
        });
    }

    private void prepareConexaoComBanco() {
        pathDatabase = System.getProperty("user.dir") + File.separator + "SEDFIORILLI.FDB";
        ipHost = "localhost";
        porta = "3055";
        user = "sysdba";
        senha = "masterkey";

        banco = new Banco(pathDatabase, ipHost, porta, user, senha);
    }

    private Parametros criaParametros() {
        Parametros parametros = new Parametros();
        parametros.setCodigo_cax_doc(Integer.parseInt(corta(boxCodigo_cax_doc.getSelectedItem().toString())));
        parametros.setCodigo_tipo_doc(Integer.parseInt(corta(boxCodigo_tipo_doc.getSelectedItem().toString())));
        parametros.setCodigo_cls_doc(Integer.parseInt(corta(boxCodigo_cls_doc.getSelectedItem().toString())));
        parametros.setExercicio(this.exercicio.getText());
        parametros.setCaminhoArquivo(this.caminhoArquivos.getText());

        return parametros;
    }

    private String corta(String item) {
        item = item.split("-")[0];
        return item.substring(0, item.length() - 1);
    }

    private boolean verificaNull() {

        if (boxCodigo_cax_doc.getSelectedItem() == null) {
            return false;
        } else if (boxCodigo_tipo_doc.getSelectedItem() == null) {
            return false;
        } else if (boxCodigo_cls_doc.getSelectedItem() == null) {
            return false;
        } else if ("".equals(this.portaBanco.getText())) {
            return false;
        } else if ("".equals(this.exercicio.getText())) {
            return false;
        } else if ("".equals(this.caminhoArquivos.getText())) {
            return false;
        }
        return true;
    }

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void selecionarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarArquivoActionPerformed
        if (verificaNull()) {
            banco.setPorta(this.portaBanco.getText());
            pdfModel.salvaPdfSelecionados(banco, criaParametros());
        } else {
            JOptionPane.showMessageDialog(null, "Todos os campos são de preenchimento obrigatório ");
        }
    }//GEN-LAST:event_selecionarArquivoActionPerformed

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed
        banco.setPorta(this.portaBanco.getText());
        pdfModel.buscaUltimo(banco);
    }//GEN-LAST:event_ultimoActionPerformed

    private void selecionarPastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarPastaActionPerformed
        if (verificaNull()) {
            banco.setPorta(this.portaBanco.getText());
            pdfModel.salvaPdfPastaSelecionada(banco, criaParametros());
        } else {
            JOptionPane.showMessageDialog(null, "Todos os campos são de preenchimento obrigatório ");
        }
    }//GEN-LAST:event_selecionarPastaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String ajuda = "Deixar o executavel na mesma pasta do Banco!!!\n"
                + "Nome do banco: SEDFIORILLI.FDB\n"
                + "Colocar o caminho dos Arquivos de acordo com configurações do Sistema!\n"
                + "Cadastrar os campos no sistema e informar corretamente antes de processar!";
        JOptionPane.showMessageDialog(null, ajuda + "");        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void portaBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portaBancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portaBancoActionPerformed

    private void exercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exercicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exercicioActionPerformed

    private void boxCodigo_tipo_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCodigo_tipo_docActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxCodigo_tipo_docActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        banco.setPorta(this.portaBanco.getText());
        if (pdfModel.verificaConexao(banco)) {
            btn.setBackground(Color.GREEN);
            btn.setText("Conectado");
            btn.setEnabled(false);
            portaBanco.setEnabled(false);
            caminhoBanco.setEnabled(false);
            preencheBox();
        } else {
            btn.setBackground(Color.RED);
            btn.setText("Conectar");
        }
    }//GEN-LAST:event_btnActionPerformed

    private void btnCaminhoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaminhoArquivoActionPerformed

        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        fc.setMultiSelectionEnabled(true);

        int returnVal = fc.showOpenDialog(fc);
        if (fc.getSelectedFile() != null) {
            caminhoArquivos.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnCaminhoArquivoActionPerformed

    private void btnCaminhoBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaminhoBancoActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("FDB file(.FDB)", "fdb");

        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(filter);
        int returnVal = fc.showOpenDialog(fc);
        if (fc.getSelectedFile() != null) {
            caminhoBanco.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnCaminhoBancoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pdf().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajuda;
    private javax.swing.JComboBox<String> boxCodigo_cax_doc;
    private javax.swing.JComboBox<String> boxCodigo_cls_doc;
    private javax.swing.JComboBox<String> boxCodigo_tipo_doc;
    private javax.swing.JButton btn;
    private javax.swing.JButton btnCaminhoArquivo;
    private javax.swing.JButton btnCaminhoBanco;
    private javax.swing.JTextField caminhoArquivos;
    private javax.swing.JTextField caminhoBanco;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JTextField exercicio;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField portaBanco;
    private javax.swing.JMenuItem selecionarArquivo;
    private javax.swing.JMenuItem selecionarPasta;
    private javax.swing.JMenuItem ultimo;
    // End of variables declaration//GEN-END:variables

}
